/* New collection — 52 prints (2026-10-04 curation).
 * Checkout links ('stripe') are '#' until wired with live Payment Links.
 * Tiers follow the approved fine-art ladder (floor $500). */

const NEW_PRODUCTS = {
  'safari-truck': {
    title: "Safari Truck",
    tagline: "A jungle cruiser, retired to the trees.",
    story: "Moss, rust, and peeling paint \u2014 this old safari truck has settled into the foliage like it grew there. Shot on a 45-megapixel frame; large-format ready up to 48\u00d760 on request.",
    image: "images/new/safari-truck.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'amber-eye': {
    title: "Amber Eye",
    tagline: "A tiger emerges from the dark.",
    story: "Shot in near-darkness, this low-key portrait finds the tiger by a single amber eye \u2014 stripe, shadow, and stare. The collection's most dramatic frame.",
    image: "images/new/amber-eye.jpg",
    collection: "wild-portraits",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'steakhouse': {
    title: "Steakhouse",
    tagline: "A corridor in black and white.",
    story: "Polished floors, receding doorways, and a single glowing sign \u2014 this black-and-white study turns a restaurant hallway into a film still.",
    image: "images/new/steakhouse.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'main-street-station': {
    title: "Main Street Station",
    tagline: "The gateway arch of every Magic Kingdom day.",
    story: "Victorian spires, a Stars-and-Stripes topper, and the bluest sky in Florida \u2014 the train station is the overture before the park even begins.",
    image: "images/new/main-street-station.jpg",
    collection: "main-street",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'ariels-greeting': {
    title: "Ariel's Greeting",
    tagline: "The mermaid waves from her clamshell.",
    story: "Ariel greets the crowd from her rolling clamshell, all teal and violet \u2014 parade-day joy, frozen mid-wave.",
    image: "images/new/ariels-greeting.jpg",
    collection: "parade",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'part-of-her-world': {
    title: "Part of Her World",
    tagline: "Arms wide to the Magic Kingdom sky.",
    story: "Mid-parade, arms thrown open to the Florida sky \u2014 Ariel at her most exuberant, framed by the park's grand facades.",
    image: "images/new/part-of-her-world.jpg",
    collection: "parade",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'pixie-dust': {
    title: "Pixie Dust",
    tagline: "Tinker Bell takes flight over the parade route.",
    story: "Tink strikes her pose atop a garden of giant blooms, wand high \u2014 mischief and magic in a single frame.",
    image: "images/new/pixie-dust.jpg",
    collection: "parade",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'bibbidi-bobbidi': {
    title: "Bibbidi-Bobbidi",
    tagline: "The Fairy Godmother works her magic.",
    story: "Wand aloft in swirling skirts of red and gold, the Fairy Godmother mid-incantation \u2014 a small frame, pure charm.",
    image: "images/new/bibbidi-bobbidi.jpg",
    collection: "parade",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'the-dragon': {
    title: "The Dragon",
    tagline: "Maleficent's dragon stalks the parade route.",
    story: "All horns and smoke, Maleficent's dragon looms over the parade \u2014 the parade's dark heart, beautifully menacing.",
    image: "images/new/the-dragon.jpg",
    collection: "parade",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'dopeys-day': {
    title: "Dopey's Day",
    tagline: "Dopey dances down Main Street.",
    story: "Dopey mid-shuffle in his oversized cap, Snow White twirling behind \u2014 the parade's happiest two minutes.",
    image: "images/new/dopeys-day.jpg",
    collection: "parade",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'jiminy': {
    title: "Jiminy",
    tagline: "The conscience takes a stroll.",
    story: "Top hat tipped and cane swinging, Jiminy Cricket struts down the parade route \u2014 dapper doesn't begin to cover it.",
    image: "images/new/jiminy.jpg",
    collection: "parade",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'no-strings': {
    title: "No Strings",
    tagline: "Pinocchio rides the parade in style.",
    story: "Pinocchio waves from his garden float, all primary colors and painted-wood grin \u2014 no strings attached.",
    image: "images/new/no-strings.jpg",
    collection: "parade",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'the-duck': {
    title: "The Duck",
    tagline: "Donald commands the parade.",
    story: "Sailor-suited and center frame, Donald works the crowd with vaudeville energy \u2014 the duck's been doing this for ninety years.",
    image: "images/new/the-duck.jpg",
    collection: "parade",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'daisy': {
    title: "Daisy",
    tagline: "Parade-day elegance, bow and all.",
    story: "Daisy takes her turn in the spotlight, bow high and spirits higher \u2014 a small, joyful frame.",
    image: "images/new/daisy.jpg",
    collection: "parade",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'main-street-cinema': {
    title: "Main Street Cinema",
    tagline: "Red awnings and coming attractions.",
    story: "The Main Street Cinema wears its 1920s marquee like a smile \u2014 all red velvet awnings and golden-age promise.",
    image: "images/new/main-street-cinema.jpg",
    collection: "main-street",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'partners': {
    title: "Partners",
    tagline: "Walt and Mickey, surveying the kingdom.",
    story: "The Partners statue catches Walt Disney mid-stride, hand in hand with Mickey, looking out over the park he imagined \u2014 rendered here in near-monochrome for the gravity the moment deserves.",
    image: "images/new/partners.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'soaring': {
    title: "Soaring",
    tagline: "An osprey rides the morning thermal.",
    story: "Wings locked in a shallow V, an osprey hangs motionless on rising air \u2014 the cheapest seat in the house, and the best view.",
    image: "images/new/soaring.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'the-commute': {
    title: "The Commute",
    tagline: "An osprey crosses dark water.",
    story: "Low over black water, wings rowing steady \u2014 the daily commute of a working raptor.",
    image: "images/new/the-commute.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'wings-up': {
    title: "Wings Up",
    tagline: "The strike position, fully committed.",
    story: "Wings thrown skyward, talons reaching \u2014 the osprey's dive begins here, in this exact geometry.",
    image: "images/new/wings-up.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'still-water': {
    title: "Still Water",
    tagline: "Sunset doubles itself on glassy water.",
    story: "The sun drops behind the skyline and the lake returns it in perfect mirror \u2014 clouds, light, and reflection in a 48-megapixel frame. Large-format ready up to 48\u00d760 on request.",
    image: "images/new/still-water.jpg",
    collection: "golden-hour",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'lamplight': {
    title: "Lamplight",
    tagline: "A lamppost silhouetted in amber.",
    story: "Wrought iron and a blazing sky \u2014 this lamppost stands sentinel as the sun goes down behind the fence line.",
    image: "images/new/lamplight.jpg",
    collection: "golden-hour",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'castle-at-dusk': {
    title: "Castle at Dusk",
    tagline: "Cinderella Castle holds the last light of the day.",
    story: "Shot on a 45-megapixel frame as the sky went amber behind Main Street, this is the castle at its most cinematic \u2014 turrets sharp against a burning sky. Large-format ready up to 48\u00d760 on request.",
    image: "images/new/castle-at-dusk.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'delivery': {
    title: "Delivery",
    tagline: "Breakfast, incoming.",
    story: "An osprey ferries a silver fish across a blue sky \u2014 the morning's work, nearly home.",
    image: "images/new/delivery.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'tianas': {
    title: "Tiana's",
    tagline: "Golden hour on the bayou water tower.",
    story: "The Tiana's Foods water tower glows at golden hour, framed by live oaks \u2014 a quiet corner of the park most visitors walk straight past.",
    image: "images/new/tianas.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'morning-kingdom': {
    title: "Morning Kingdom",
    tagline: "The castle in soft morning light.",
    story: "Before the crowds arrive, the castle stands in pastel quiet \u2014 blue turrets, soft sky, and the whole day ahead.",
    image: "images/new/morning-kingdom.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'monorail': {
    title: "Monorail",
    tagline: "The highway in the sky.",
    story: "The Mark VI glides past Spaceship Earth, orange stripe flashing \u2014 sixty years of tomorrow, still arriving on time.",
    image: "images/new/monorail.jpg",
    collection: "rides",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'minnies-balloon': {
    title: "Minnie's Balloon",
    tagline: "A polka-dot balloon drifts over the gardens.",
    story: "A Minnie balloon tugs at its string above the flower beds \u2014 the park's lightest moment, floating.",
    image: "images/new/minnies-balloon.jpg",
    collection: "rides",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'topiary': {
    title: "Topiary",
    tagline: "A dinosaur in boxwood, mid-roar.",
    story: "Part garden, part Muppet \u2014 this boxwood beast guards the flower beds with its tongue out and teeth bared.",
    image: "images/new/topiary.jpg",
    collection: "rides",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'mickeys-of-hollywood': {
    title: "Mickey's of Hollywood",
    tagline: "Neon script over the boulevard.",
    story: "The Mickey's of Hollywood sign glows red against the night \u2014 the boulevard's brightest hello.",
    image: "images/new/mickeys-of-hollywood.jpg",
    collection: "rides",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'toy-story': {
    title: "Toy Story",
    tagline: "Woody and Rex ride the rails.",
    story: "Woody lassos the sky while Rex brings up the rear \u2014 Slinky Dog Dash at full tilt, shot at golden hour.",
    image: "images/new/toy-story.jpg",
    collection: "rides",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'sci-fi': {
    title: "Sci-Fi",
    tagline: "Neon nostalgia from a drive-in that never was.",
    story: "The Sci-Fi Dine-In sign is pure 1950s futurism \u2014 atomic-age lettering promising dinner under the stars, indoors.",
    image: "images/new/sci-fi.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-majestic': {
    title: "The Majestic",
    tagline: "Art Deco verticality on Hollywood Boulevard.",
    story: "A blade sign in cream and teal rises past moody clouds \u2014 the golden age of Hollywood, distilled to geometry and light.",
    image: "images/new/the-majestic.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'plutos-perch': {
    title: "Pluto's Perch",
    tagline: "The pup surveys his kingdom from on high.",
    story: "Pluto keeps watch from his rooftop perch, golden against a stormy sky \u2014 a small frame with a big personality.",
    image: "images/new/plutos-perch.jpg",
    collection: "main-street",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'prospect-avenue': {
    title: "Prospect Avenue",
    tagline: "A green light on a studio backlot street.",
    story: "A vintage traffic signal glows green beneath the Prospect Avenue sign \u2014 Hollywood's backlot America, frozen between takes.",
    image: "images/new/prospect-avenue.jpg",
    collection: "main-street",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'mickeys-after-dark': {
    title: "Mickey's After Dark",
    tagline: "Neon script against the night.",
    story: "The Mickey's of Hollywood sign burns white-hot against black sky \u2014 the park's brightest signature, shot after dark.",
    image: "images/new/mickeys-after-dark.jpg",
    collection: "main-street",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'chinese-theatre': {
    title: "The Chinese Theatre",
    tagline: "Dusk settles over Hollywood's grandest facade.",
    story: "Palm silhouettes and a brooding sky frame the Chinese Theatre as its marquee flickers on \u2014 the park's love letter to cinema's golden age.",
    image: "images/new/chinese-theatre.jpg",
    collection: "main-street",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'main-street-soda': {
    title: "Main Street Soda",
    tagline: "Coca-Cola red and window-glow warmth.",
    story: "A shop window dressed in Coca-Cola red, glowing from within \u2014 Main Street's sweetest still life.",
    image: "images/new/main-street-soda.jpg",
    collection: "main-street",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'tie-sunset': {
    title: "TIE Sunset",
    tagline: "A TIE fighter against a burning Batuu sky.",
    story: "A TIE fighter sits silhouetted as the sun drops behind Black Spire's petrified forest \u2014 Star Wars as pure western.",
    image: "images/new/tie-sunset.jpg",
    collection: "galaxys-edge",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'batuu-rainbow': {
    title: "Batuu Rainbow",
    tagline: "A rainbow breaks over Galaxy's Edge.",
    story: "Storm light, a fading rainbow, and the spires of Batuu \u2014 the outpost at its most otherworldly.",
    image: "images/new/batuu-rainbow.jpg",
    collection: "galaxys-edge",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-falcon': {
    title: "The Falcon",
    tagline: "The fastest hunk of junk in the galaxy, at rest.",
    story: "The Millennium Falcon sits in Docking Bay 7, every panel and greeble rendered in warm late light \u2014 the ship every kid dreamed of, life-size.",
    image: "images/new/the-falcon.jpg",
    collection: "galaxys-edge",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'black-spire': {
    title: "Black Spire",
    tagline: "The petrified forest of Batuu.",
    story: "Batuu's ancient spires rise like a stone forest at golden hour \u2014 the land's alien geology doing all the talking.",
    image: "images/new/black-spire.jpg",
    collection: "galaxys-edge",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'alien-saucers': {
    title: "Alien Swirling Saucers",
    tagline: "Neon green over Toy Story Land.",
    story: "The Alien Swirling Saucers sign burns green and red into the dusk \u2014 the land's loudest, proudest marquee.",
    image: "images/new/alien-saucers.jpg",
    collection: "rides",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'victorian-main-street': {
    title: "Victorian Main Street",
    tagline: "Gingerbread architecture in full color.",
    story: "Candy-striped awnings and a stars-and-stripes topper \u2014 Main Street's Victorian facades are maximalism done right.",
    image: "images/new/victorian-main-street.jpg",
    collection: "main-street",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-crane': {
    title: "The Crane",
    tagline: "A red-crowned crane in close portrait.",
    story: "Crimson crown, amber eye, dagger bill \u2014 this crane portrait is all aristocratic menace, rendered feather by feather.",
    image: "images/new/the-crane.jpg",
    collection: "on-the-wing",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'killdeer': {
    title: "Killdeer",
    tagline: "A small plover on rocky ground.",
    story: "All big eyes and broken-wing theatrics \u2014 the killdeer holds its ground on a bed of gravel.",
    image: "images/new/killdeer.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'touchdown': {
    title: "Touchdown",
    tagline: "A mallard drops in, wings braking.",
    story: "Wings cupped and feet down, a mallard hen arrives on the water \u2014 the last second of flight.",
    image: "images/new/touchdown.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'shake-down': {
    title: "Shake Down",
    tagline: "Water flies as a mallard shakes off.",
    story: "A burst of spray and ruffled feathers \u2014 a mallard shakes the lake off its back in a 22-megapixel freeze-frame.",
    image: "images/new/shake-down.jpg",
    collection: "on-the-wing",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'iridescence': {
    title: "Iridescence",
    tagline: "Backlit feathers, feather by feather.",
    story: "Low sun turns a duck's crown into beaten copper \u2014 an intimate study of feather and light.",
    image: "images/new/iridescence.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'last-cast': {
    title: "Last Cast",
    tagline: "A lone angler works the evening water.",
    story: "A fisherman stands small against a wide amber river at dusk \u2014 solitude, rendered in a 45-megapixel frame. Large-format ready up to 48\u00d760 on request.",
    image: "images/new/last-cast.jpg",
    collection: "golden-hour",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'fire-plug': {
    title: "Fire Plug",
    tagline: "A hydrant in full parade dress.",
    story: "Chipped paint in carnival colors, a songbird on top for scale \u2014 this fire hydrant is a small-town monument. Shot on a 45-megapixel frame; large-format ready up to 48\u00d760 on request.",
    image: "images/new/fire-plug.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-cardinal': {
    title: "The Cardinal",
    tagline: "Crimson against a soft sky.",
    story: "A northern cardinal in full crimson, beak like a sealing-wax stamp \u2014 the backyard bird as fine art.",
    image: "images/new/the-cardinal.jpg",
    collection: "on-the-wing",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-getaway': {
    title: "The Getaway",
    tagline: "A '60s coupe idles outside the garage.",
    story: "Two-tone paint, whitewalls, and an empty lot \u2014 this coupe looks ready to outrun something. Pure American asphalt poetry.",
    image: "images/new/the-getaway.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
};

const COLLECTIONS = {
  "main-street": "Main Street & Icons",
  "parade": "Parade Day",
  "galaxys-edge": "Galaxy's Edge",
  "rides": "Rides in Motion",
  "americana": "Americana",
  "golden-hour": "Golden Hour",
  "on-the-wing": "On the Wing",
  "wild-portraits": "Wild Portraits",
};
