/* New collection — 14 prints (2026-10-04 curation).
 * Checkout links ('stripe') are '#' until wired with live Payment Links.
 * Tiers follow the approved fine-art ladder (floor $500). */

const NEW_PRODUCTS = {
  'amber-eye': {
    title: "Amber Eye",
    tagline: "A tiger emerges from the dark.",
    story: "Shot in near-darkness, this low-key portrait finds the tiger by a single amber eye \u2014 stripe, shadow, and stare. The collection's most dramatic frame.",
    image: "images/new/amber-eye.jpg",
    collection: "wild-portraits",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'soaring': {
    title: "Soaring",
    tagline: "An osprey rides the morning thermal.",
    story: "Wings locked in a shallow V, an osprey hangs motionless on rising air \u2014 the cheapest seat in the house, and the best view.",
    image: "images/new/soaring.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'the-commute': {
    title: "The Commute",
    tagline: "An osprey crosses dark water.",
    story: "Low over black water, wings rowing steady \u2014 the daily commute of a working raptor.",
    image: "images/new/the-commute.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'wings-up': {
    title: "Wings Up",
    tagline: "The strike position, fully committed.",
    story: "Wings thrown skyward, talons reaching \u2014 the osprey's dive begins here, in this exact geometry.",
    image: "images/new/wings-up.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'delivery': {
    title: "Delivery",
    tagline: "Breakfast, incoming.",
    story: "An osprey ferries a silver fish across a blue sky \u2014 the morning's work, nearly home.",
    image: "images/new/delivery.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'the-crane': {
    title: "The Crane",
    tagline: "A red-crowned crane in close portrait.",
    story: "Crimson crown, amber eye, dagger bill \u2014 this crane portrait is all aristocratic menace, rendered feather by feather.",
    image: "images/new/the-crane.jpg",
    collection: "on-the-wing",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'killdeer': {
    title: "Killdeer",
    tagline: "A small plover on rocky ground.",
    story: "All big eyes and broken-wing theatrics \u2014 the killdeer holds its ground on a bed of gravel.",
    image: "images/new/killdeer.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'touchdown': {
    title: "Touchdown",
    tagline: "A mallard drops in, wings braking.",
    story: "Wings cupped and feet down, a mallard hen arrives on the water \u2014 the last second of flight.",
    image: "images/new/touchdown.jpg",
    collection: "on-the-wing",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: '#' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: '#' },
    ],
  },
  'shake-down': {
    title: "Shake Down",
    tagline: "Water flies as a mallard shakes off.",
    story: "A burst of spray and ruffled feathers \u2014 a mallard shakes the lake off its back in a 22-megapixel freeze-frame.",
    image: "images/new/shake-down.jpg",
    collection: "on-the-wing",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'iridescence': {
    title: "Iridescence",
    tagline: "Backlit feathers, feather by feather.",
    story: "Low sun turns a duck's crown into beaten copper \u2014 an intimate study of feather and light.",
    image: "images/new/iridescence.jpg",
    collection: "on-the-wing",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: '#' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: '#' },
    ],
  },
  'last-cast': {
    title: "Last Cast",
    tagline: "A lone angler works the evening water.",
    story: "A fisherman stands small against a wide amber river at dusk \u2014 solitude, rendered in a 45-megapixel frame. Large-format ready up to 48\u00d760 on request.",
    image: "images/new/last-cast.jpg",
    collection: "golden-hour",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'fire-plug': {
    title: "Fire Plug",
    tagline: "A hydrant in full parade dress.",
    story: "Chipped paint in carnival colors, a songbird on top for scale \u2014 this fire hydrant is a small-town monument. Shot on a 45-megapixel frame; large-format ready up to 48\u00d760 on request.",
    image: "images/new/fire-plug.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
  'the-getaway': {
    title: "The Getaway",
    tagline: "A '60s coupe idles outside the garage.",
    story: "Two-tone paint, whitewalls, and an empty lot \u2014 this coupe looks ready to outrun something. Pure American asphalt poetry.",
    image: "images/new/the-getaway.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: '#' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: '#' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: '#' },
    ],
  },
};

const COLLECTIONS = {
  "americana": "Americana",
  "golden-hour": "Golden Hour",
  "on-the-wing": "On the Wing",
  "wild-portraits": "Wild Portraits",
};
