/* New collection — 14 prints (2026-10-04 curation).
 * Checkout links ('stripe') are '#' until wired with live Payment Links.
 * Tiers follow the approved fine-art ladder (floor $500). */

const NEW_PRODUCTS = {
  'amber-eye': {
    title: "Amber Eye",
    tagline: "A tiger emerges from the dark.",
    story: "Shot in near-darkness, this low-key portrait finds the tiger by a single amber eye \u2014 stripe, shadow, and stare. The collection's most dramatic frame.",
    image: "images/new/amber-eye.jpg",
    collection: "mammals",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/7sY5kCb8Uawh9P3cI23Ru14' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/7sYdR85OAdIt8KZ6jE3Ru15' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/00w8wO0ug33P0et5fA3Ru16' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/6oUbJ04Kw9sde5j37s3Ru17' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/3cI28q7WI1ZLgdr0Zk3Ru18' },
    ],
  },
  'soaring': {
    title: "Soaring",
    tagline: "An osprey rides the morning thermal.",
    story: "Wings locked in a shallow V, an osprey hangs motionless on rising air \u2014 the cheapest seat in the house, and the best view.",
    image: "images/new/soaring.jpg",
    collection: "osprey",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: 'https://buy.stripe.com/00w9AS2CobAl1ixcI23Ru19' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/aFa28qb8U5bX0etdM63Ru1a' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: 'https://buy.stripe.com/eVq28qfpaeMxbXbcI23Ru1b' },
    ],
  },
  'the-commute': {
    title: "The Commute",
    tagline: "An osprey crosses dark water.",
    story: "Low over black water, wings rowing steady \u2014 the daily commute of a working raptor.",
    image: "images/new/the-commute.jpg",
    collection: "osprey",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: 'https://buy.stripe.com/6oU8wO6SEeMx8KZ6jE3Ru1c' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/eVq8wOel69sd6CRdM63Ru1d' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: 'https://buy.stripe.com/28E6oG2Co0VHe5jazU3Ru1e' },
    ],
  },
  'wings-up': {
    title: "Wings Up",
    tagline: "The strike position, fully committed.",
    story: "Wings thrown skyward, talons reaching \u2014 the osprey's dive begins here, in this exact geometry.",
    image: "images/new/wings-up.jpg",
    collection: "osprey",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: 'https://buy.stripe.com/00w5kCb8UeMxbXbazU3Ru1f' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/aFa28qgteeMx8KZfUe3Ru1g' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: 'https://buy.stripe.com/6oUcN4el60VH3qFgYi3Ru1h' },
    ],
  },
  'delivery': {
    title: "Delivery",
    tagline: "Breakfast, incoming.",
    story: "An osprey ferries a silver fish across a blue sky \u2014 the morning's work, nearly home.",
    image: "images/new/delivery.jpg",
    collection: "osprey",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/14A7sKgtecEpaT737s3Ru1i' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: 'https://buy.stripe.com/28EdR87WIcEp5yNazU3Ru1j' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: 'https://buy.stripe.com/28E8wOb8U7k53qFfUe3Ru1k' },
    ],
  },
  'the-crane': {
    title: "The Crane",
    tagline: "A red-crowned crane in close portrait.",
    story: "Crimson crown, amber eye, dagger bill \u2014 this crane portrait is all aristocratic menace, rendered feather by feather.",
    image: "images/new/the-crane.jpg",
    collection: "water-birds",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/aFabJ04KwbAl2mBeQa3Ru1l' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/3cI9AS6SEawh7GV4bw3Ru1m' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/9B600i90M33P8KZ37s3Ru1n' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/00w14mfpa1ZLf9n6jE3Ru1o' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/eVq4gy2CocEp9P34bw3Ru1p' },
    ],
  },
  'killdeer': {
    title: "Killdeer",
    tagline: "A small plover on rocky ground.",
    story: "All big eyes and broken-wing theatrics \u2014 the killdeer holds its ground on a bed of gravel.",
    image: "images/new/killdeer.jpg",
    collection: "water-birds",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/4gM28qb8U9sd0etgYi3Ru1q' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: 'https://buy.stripe.com/4gM14mfpaawhd1f8rM3Ru1r' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: 'https://buy.stripe.com/fZueVc6SEfQBgdr9vQ3Ru1s' },
    ],
  },
  'touchdown': {
    title: "Touchdown",
    tagline: "A mallard drops in, wings braking.",
    story: "Wings cupped and feet down, a mallard hen arrives on the water \u2014 the last second of flight.",
    image: "images/new/touchdown.jpg",
    collection: "ducks",
    badge: "Up to 16 \u00d7 20",
    maxNote: "Available up to 16\u00d720.",
    options: [
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/4gMcN4dh233P2mB8rM3Ru1t' },
      { label: "16 \u00d7 20 in", detail: "Fine-art poster, unframed", price: 850, stripe: 'https://buy.stripe.com/dRm5kCfpa1ZLaT75fA3Ru1u' },
      { label: "16 \u00d7 20 in", detail: "Framed print, black wood", price: 1400, stripe: 'https://buy.stripe.com/dRm6oG5OA5bX9P34bw3Ru1v' },
    ],
  },
  'shake-down': {
    title: "Shake Down",
    tagline: "Water flies as a mallard shakes off.",
    story: "A burst of spray and ruffled feathers \u2014 a mallard shakes the lake off its back in a 22-megapixel freeze-frame.",
    image: "images/new/shake-down.jpg",
    collection: "ducks",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/5kQdR87WI7k51ixazU3Ru1w' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/fZuaEWel6eMx4uJcI23Ru1x' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/7sYaEW5OAgUF0et5fA3Ru1y' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/aFa7sKdh2gUF2mBeQa3Ru1z' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/fZu7sKa4QeMx8KZazU3Ru1A' },
    ],
  },
  'iridescence': {
    title: "Iridescence",
    tagline: "Backlit feathers, feather by feather.",
    story: "Low sun turns a duck's crown into beaten copper \u2014 an intimate study of feather and light.",
    image: "images/new/iridescence.jpg",
    collection: "ducks",
    badge: "Small format",
    maxNote: "Offered up to 11\u00d714 to keep every feather crisp.",
    options: [
      { label: "8 \u00d7 10 in", detail: "Fine-art poster, unframed", price: 500, stripe: 'https://buy.stripe.com/fZueVc7WIgUF8KZfUe3Ru1B' },
      { label: "11 \u00d7 14 in", detail: "Fine-art poster, unframed", price: 650, stripe: 'https://buy.stripe.com/14A4gyfpa7k51ixbDY3Ru1C' },
      { label: "11 \u00d7 14 in", detail: "Framed print, black wood", price: 1100, stripe: 'https://buy.stripe.com/14A4gy5OA7k53qFdM63Ru1D' },
    ],
  },
  'last-cast': {
    title: "Last Cast",
    tagline: "A lone angler works the evening water.",
    story: "A fisherman stands small against a wide amber river at dusk \u2014 solitude, rendered in a 45-megapixel frame. Large-format ready up to 48\u00d760 on request.",
    image: "images/new/last-cast.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/5kQ6oGel6bAld1fdM63Ru1E' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/cNi8wO0ugeMx7GV0Zk3Ru1F' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/00waEWel6cEp4uJ8rM3Ru1G' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/14A9AS4KwbAl3qF0Zk3Ru1H' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/14AaEW3Gs0VH8KZazU3Ru1I' },
    ],
  },
  'fire-plug': {
    title: "Fire Plug",
    tagline: "A hydrant in full parade dress.",
    story: "Chipped paint in carnival colors, a songbird on top for scale \u2014 this fire hydrant is a small-town monument. Shot on a 45-megapixel frame; large-format ready up to 48\u00d760 on request.",
    image: "images/new/fire-plug.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/9B614m90M5bX2mB4bw3Ru1J' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/00w8wO2Co7k56CReQa3Ru1K' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/fZucN42Co33PbXb8rM3Ru1L' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/5kQ3cu6SEawh6CR4bw3Ru1M' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/8x23cudh2dIt2mBbDY3Ru1N' },
    ],
  },
  'the-getaway': {
    title: "The Getaway",
    tagline: "A '60s coupe idles outside the garage.",
    story: "Two-tone paint, whitewalls, and an empty lot \u2014 this coupe looks ready to outrun something. Pure American asphalt poetry.",
    image: "images/new/the-getaway.jpg",
    collection: "americana",
    badge: "Large format ready",
    maxNote: "Available up to 24\u00d736 \u2014 printed from the full-resolution original.",
    options: [
      { label: "12 \u00d7 18 in", detail: "Fine-art poster, unframed", price: 750, stripe: 'https://buy.stripe.com/6oU4gyccYdIt3qFbDY3Ru1O' },
      { label: "18 \u00d7 24 in", detail: "Fine-art poster, unframed", price: 950, stripe: 'https://buy.stripe.com/bJe7sKgte9sdbXbfUe3Ru1P' },
      { label: "24 \u00d7 36 in", detail: "Fine-art poster, unframed", price: 1200, stripe: 'https://buy.stripe.com/cNi8wO1yk1ZL7GV6jE3Ru1Q' },
      { label: "18 \u00d7 24 in", detail: "Framed print, black wood", price: 1600, stripe: 'https://buy.stripe.com/cNi5kCgte5bX7GV6jE3Ru1R' },
      { label: "24 \u00d7 36 in", detail: "Gallery canvas", price: 1800, stripe: 'https://buy.stripe.com/7sY00i1yk47T0etazU3Ru1S' },
    ],
  },
};

